import pandas as pd
import matplotlib.pyplot as plt
import os

# =============================================================================
#  Plot BER Curves for NSC Viterbi Decoder
#  ---------------------------------------------------------------------------
#  - Input : results/ber_result.csv (generated by main_test.c)
#      Columns = EbN0_dB, BER_soft, BER_hard, BER_bpsk
#  - Output: images/ber_curve.pdf, images/ber_curve.png
#
#  本スクリプトは、論文・研究資料用の高品質な BER 図を生成する。
# =============================================================================

# ▼ 出力フォルダ（images/）が無い場合は自動作成
os.makedirs("images", exist_ok=True)

# =============================================================================
#  Matplotlib フォント設定（論文向け）
#  Times New Roman + STIX 数式 = IEEE / Elsevier でも通用する組み合わせ
# =============================================================================
plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams["mathtext.fontset"] = "stix"
plt.rcParams["font.size"] = 14

# =============================================================================
#  Load CSV data
# =============================================================================
df = pd.read_csv("results/ber_result.csv")  # main_test.c が出力するCSV

EbN0 = df["EbN0_dB"]
ber_soft = df["BER_soft"]
ber_hard = df["BER_hard"]
ber_bpsk = df["BER_bpsk"]

# =============================================================================
#  Create BER figure
# =============================================================================
plt.figure(figsize=(7.5, 6))

# --- Soft-decision Viterbi ---
plt.semilogy(
    EbN0,
    ber_soft,
    marker="o",
    markersize=8,
    markerfacecolor="none",
    markeredgewidth=1.8,
    linewidth=2.5,
    label="Soft-decision Viterbi",
)

# --- Hard-decision Viterbi ---
plt.semilogy(
    EbN0,
    ber_hard,
    marker="s",
    markersize=8,
    markerfacecolor="none",
    markeredgewidth=1.8,
    linewidth=2.5,
    label="Hard-decision Viterbi",
)

# --- Uncoded BPSK theoretical BER ---
plt.semilogy(
    EbN0,
    ber_bpsk,
    marker="^",
    markersize=8,
    markerfacecolor="none",
    markeredgewidth=1.8,
    linewidth=2.5,
    label="Uncoded BPSK (theory)",
)

# Y 軸スケール
plt.ylim(1e-5, 1)

# 軸ラベル
plt.xlabel("Eb/N0 [dB]", fontsize=18)
plt.ylabel("Bit Error Rate (BER)", fontsize=18)

# グリッド（対数軸向け）
plt.grid(True, which="both", linestyle="--", linewidth=0.6, alpha=0.6)

# 凡例
plt.legend(fontsize=14, loc="upper right", frameon=True, edgecolor="black")

plt.tight_layout()

# =============================================================================
#  Save figure in high resolution (論文品質)
# =============================================================================
plt.savefig("images/ber_curve.pdf", dpi=300, bbox_inches="tight")  # Vector format
plt.savefig("images/ber_curve.png", dpi=300, bbox_inches="tight")  # Raster format

plt.show()
